class Worksheet {
  final String id;
  final String title;
  final String goal;
  final int estimatedMinutes;
  final String content;
  final List<String> steps;

  Worksheet({
    required this.id,
    required this.title,
    required this.goal,
    required this.estimatedMinutes,
    required this.content,
    required this.steps,
  });

  static List<Worksheet> getWorksheets() {
    return [
      Worksheet(
        id: 'WS01',
        title: 'Getting Started with Smart Factory',
        goal: 'Learn the basics of the Smart Factory control system',
        estimatedMinutes: 15,
        content: 'Introduction to the Smart Factory system and its components.',
        steps: [
          'Open the Home screen and identify the status card',
          'Locate the Start, Stop, and Reset Faults buttons',
          'Observe the live metrics display',
          'Check the connection badge showing Simulation mode',
        ],
      ),
      Worksheet(
        id: 'WS02',
        title: 'Data Logging Basics',
        goal: 'Learn how to log data on the factory',
        estimatedMinutes: 20,
        content: 'Understanding how the system logs events and metrics.',
        steps: [
          'Start a production run from the Home screen',
          'Navigate to Analytics to see live data',
          'Observe the metrics being recorded',
          'Export a CSV file for analysis',
        ],
      ),
      Worksheet(
        id: 'WS03',
        title: 'Conveyor Control',
        goal: 'Master conveyor speed control and operation',
        estimatedMinutes: 25,
        content: 'Learn how to control the conveyor system safely.',
        steps: [
          'Go to the Run screen',
          'Adjust the conveyor speed slider',
          'Start the system and observe speed changes',
          'Practice stopping and starting safely',
        ],
      ),
      Worksheet(
        id: 'WS04',
        title: 'Sensor Introduction',
        goal: 'Understand the different sensor types',
        estimatedMinutes: 30,
        content: 'Learn about optical, inductive, and capacitive sensors.',
        steps: [
          'Navigate to the I/O screen',
          'Identify the First Gate sensor',
          'Observe the Inductive sensor (detects steel)',
          'Watch the Capacitive sensor (detects aluminium)',
          'Study the Photo Gate sensor',
        ],
      ),
      Worksheet(
        id: 'WS05',
        title: 'Material Sorting',
        goal: 'Learn how materials are automatically sorted',
        estimatedMinutes: 35,
        content: 'Understanding the automatic sorting logic.',
        steps: [
          'Start a sorting run',
          'Watch how steel triggers the inductive sensor',
          'Observe aluminium detection via capacitive sensor',
          'See plastic items pass through to the end',
          'Check the counters on the Run screen',
        ],
      ),
      Worksheet(
        id: 'WS06',
        title: 'Manual Jog Operations',
        goal: 'Practice manual control of system components',
        estimatedMinutes: 20,
        content: 'Learn to safely jog actuators manually.',
        steps: [
          'Ensure the system is stopped',
          'Use the manual jog area on Run screen',
          'Test the conveyor jog button',
          'Try the left paddle (steel)',
          'Try the right paddle (aluminium)',
          'Test the plunger (observe safety interlocks)',
        ],
      ),
      Worksheet(
        id: 'WS07',
        title: 'Understanding FPY',
        goal: 'Calculate First Pass Yield from production data',
        estimatedMinutes: 25,
        content: 'Learn how to calculate and interpret FPY.',
        steps: [
          'Run a batch of 50 items',
          'Note the good items count',
          'Note the reject count',
          'Calculate FPY: (good / total) × 100',
          'Compare with the displayed FPY metric',
        ],
      ),
      Worksheet(
        id: 'WS08',
        title: 'Throughput Analysis',
        goal: 'Analyze throughput at different speeds',
        estimatedMinutes: 30,
        content: 'Understanding throughput and how speed affects it.',
        steps: [
          'Set conveyor speed to 25%',
          'Run for 2 minutes and note throughput',
          'Set speed to 50%',
          'Run for 2 minutes and note throughput',
          'Set speed to 75%',
          'Run for 2 minutes and note throughput',
          'Plot the relationship between speed and throughput',
        ],
      ),
      Worksheet(
        id: 'WS09',
        title: 'Safety Interlocks',
        goal: 'Understand the safety systems',
        estimatedMinutes: 20,
        content: 'Learn about interlocks that prevent unsafe operations.',
        steps: [
          'Try to activate the plunger while conveyor is running',
          'Observe the safety interlock message',
          'Stop the conveyor and try again',
          'Trigger an E-Stop fault in Settings',
          'Try to start the system (should be blocked)',
          'Reset faults and verify system recovers',
        ],
      ),
      Worksheet(
        id: 'WS10',
        title: 'Emergency Stop Procedures',
        goal: 'Learn proper E-Stop procedures',
        estimatedMinutes: 15,
        content: 'Understanding emergency stop functionality.',
        steps: [
          'Start a production run',
          'Go to Settings and inject an E-Stop fault',
          'Observe all outputs are disabled',
          'Note the red status on Home screen',
          'Use Reset Faults to clear',
          'Verify system can restart',
        ],
      ),
      Worksheet(
        id: 'WS11',
        title: 'Batch Production',
        goal: 'Run a complete batch from start to finish',
        estimatedMinutes: 40,
        content: 'Complete a full production batch.',
        steps: [
          'Set batch target to 100 items',
          'Choose the sorting recipe',
          'Start production',
          'Monitor progress on Run screen',
          'Watch for batch completion',
          'Review final metrics',
        ],
      ),
      Worksheet(
        id: 'WS12',
        title: 'Pneumatic Systems',
        goal: 'Understand pneumatic pick and place',
        estimatedMinutes: 25,
        content: 'Learn about pneumatic actuators and vacuum grippers.',
        steps: [
          'Study the plunger down output',
          'Understand the vacuum gripper output',
          'Test the plunger in manual mode',
          'Observe the gantry home sensor',
          'Test gantry step and direction controls',
        ],
      ),
      Worksheet(
        id: 'WS13',
        title: 'Fault Diagnosis',
        goal: 'Learn to identify and diagnose faults',
        estimatedMinutes: 35,
        content: 'Practice diagnosing common faults.',
        steps: [
          'Inject a sensor stuck fault',
          'Observe the rising reject rate',
          'Use I/O screen to identify stuck sensor',
          'Clear the fault',
          'Inject a paddle jam fault',
          'Diagnose using counters and I/O',
        ],
      ),
      Worksheet(
        id: 'WS14',
        title: 'Data Export and Analysis',
        goal: 'Export and analyze production data',
        estimatedMinutes: 30,
        content: 'Learn to export data for detailed analysis.',
        steps: [
          'Run production for 15 minutes',
          'Go to Analytics screen',
          'Select "Last 15 minutes" time window',
          'Export metrics CSV',
          'Export event log CSV',
          'Open files and review data structure',
        ],
      ),
      Worksheet(
        id: 'WS15',
        title: 'IO-Link Introduction',
        goal: 'Understand IO-Link concepts',
        estimatedMinutes: 20,
        content: 'Learn about IO-Link smart sensor technology.',
        steps: [
          'Read about IO-Link protocol',
          'Understand how sensors communicate data',
          'Learn about parameterization',
          'Study diagnostics capabilities',
          'Review IO-Link benefits in Industry 4.0',
        ],
      ),
      Worksheet(
        id: 'WS16',
        title: 'Predictive Maintenance',
        goal: 'Interpret trends to predict maintenance needs',
        estimatedMinutes: 40,
        content: 'Learn to spot trends that indicate maintenance is needed.',
        steps: [
          'Run production in normal mode',
          'Enable random faults in Settings',
          'Monitor the reject rate trend',
          'Identify when reject rate starts rising',
          'Correlate with potential component wear',
          'Plan preventive maintenance',
        ],
      ),
      Worksheet(
        id: 'WS17',
        title: 'Advanced Analytics',
        goal: 'Master all analytics features',
        estimatedMinutes: 45,
        content: 'Complete analysis of all performance metrics.',
        steps: [
          'Review throughput chart over 10 minutes',
          'Analyze FPY trends',
          'Study rejects per minute bar chart',
          'Calculate OEE manually',
          'Compare speed vs quality trade-offs',
          'Export comprehensive report',
          'Prepare recommendations for optimization',
        ],
      ),
    ];
  }
}
